services:
  - type: web
    name: dry-delicious
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PRODUCTION_DOMAIN
        sync: false
      - key: NODEMAILER_EMAIL
        sync: false
      - key: NODEMAILER_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
